### ISSUE TITLE
TPM 2.0 Lib Spec version 1.38

### ISSUE THREAD

**Issue by moso1** [stwagnr/tpm2simulator#3]
It seems the script supports TPM 2.0 Lib Spec version 1.38 but I couldn't get it to work.
To start with, please submit documents/138/...
I've tried to put in 1.38 pdfs myself but I get this error:

cmake -G "Unix Makefiles" ../cmake -DCMAKE_BUILD_TYPE=Debug -DSPEC_VERSION=138
Extracting source code for the TPM simulator version 138 (this may take a while)
updating version to 138
Reading ../documents/138/TPM Rev 2.0 Part 2 - Structures 01.38.fodt
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    structures_file = file_handler.get_fd(settings.TPM20_SPEC_STRUCTURES)
  File "/home/<user>/tpm2simulator/scripts/modules/file_handling.py", line 40, in get_fd
    f = open(file_name)
IOError: [Errno 2] No such file or directory: '../documents/138/TPM Rev 2.0 Part 2 - Structures 01.38.fodt'
CMake Error at CMakeLists.txt:39 (MESSAGE):
  ERROR: Please update settings.py in the directory 'script'

**Comment by stwagnr** [comment]
The previous version of the script supported the **unpublished** version of the TPM 2.0 Library Specification version 01.38 (a Microsoft Word document only available to members of the Trusted Computing Group), which we usually convert to an _fodt_ (OpenDocument Flat XML Document) document and then extract the code. That is why the output says:

> Reading ../documents/138/TPM Rev 2.0 Part 2 - Structures 01.38.fodt

However, since those _fodt_ documents are directly based on TCG-internal _docx_ (Microsoft Word) documents, we are not able to publish those _fodt_/_docx_ files. They are confidential and you have to be a member of TCG to get those documents.

Fortunately, our script also works with the _pdf_/_txt_ version of the specification, including 01.38.
I actually had this code for a while now, but haven't found the time to update the repository until today.
So, after a pull, you should be able to build a simulator based on specification 01.38 (as well as 01.16).

**Comment by moso1** [comment]
I pulled again and cmake 138 works now. But make fails. Do I miss something?

[100%] Linking C executable Simulator
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `BnMult'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `BnDiv'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `BnCurveInitialize'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `BnEccModMult2'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `SupportLibInit'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `TDES_encrypt'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `BnModMult'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `BnGcd'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `BnModExp'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `OsslContextLeave'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `TDES_set_encrypt_key'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `TDES_decrypt'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `BnModInverse'
/home//tpm2simulator/build/tpm/libTPM.so: undefined reference to `BnEccModMult'

**Comment by stwagnr** [comment]
I would recommend deleting the `build` folder and start from scratch.

If that does not help, I would check the cmake files, which link the crypto engine libraries, because those references look like references to OpenSSL (the relevant shared libraries and headers are located in the folder `lib` and should work as for version 01.16).

**Comment by moso1** [comment]
I've deleted the whole project, re-clone it, update settings.py, cmake 138, make and 1.38 still doesn't work. cmake 116 and make still works. I'm using the OpenSSL 1.0.2g headers. 
Can you tell me if you can build 1.38 simulator with the prebuilt lib/libeay32.lib?

**Comment by stwagnr** [comment]
I have committed a change for a cmake file, which should fix the undefined references in version 01.38.
Could you please pull, delete the directories `build`and `src` and then try again?

**Comment by moso1** [comment]
It works now! You're awesome! This project is super!
